build:
  nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
                    - command: phpunit --coverage-clover=my-coverage.xml
                      coverage:
                        file: coverage.xml   # <- Set this to where we find the coverage data.
                                                    #    The path is relative to the current directory.
                        format: clover
  environment:
    php:
      version: 7.2
      
filter:
    excluded_paths: [vendor/*, tests/*]
    
checks:
    php:
        code_rating: true
        duplication: true
        
tools:
    external_code_coverage: false
    php_mess_detector: true
    sensiolabs_security_checker: true
