build:
  nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
                    - command: composer update
  environment:
    php:
      version: 7.2
      
filter:
    excluded_paths: [vendor/*, tests/*]
    
checks:
    php:
        code_rating: true
        duplication: true
        
tools:
    external_code_coverage: false
    php_mess_detector: true
    sensiolabs_security_checker: true
