language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - master

matrix:
  allow_failures:
    - php: master
  fast_finish: true
  
script: composer update
